name: 'take_home'
version: '1.0.0'

profile: 'default'

config-version: 2

vars:
  dbt_date:time_zone: "UTC"
  dblink_host: "{{ env_var('DBLINK_HOST') }}"
  dblink_dbname: "{{ env_var('DBLINK_DBNAME') }}"
  dblink_user: "{{ env_var('DBLINK_USER') }}"
  dblink_password: "{{ env_var('DBLINK_PASSWORD') }}"

models:
  take_home:
    +materialized: table

    bronze:
      +schema: bronze
      +materialized: view

    silver:
      +schema: silver
      +materialized: table

    gold:
      +schema: gold
      +materialized: table
    
    data_marts:
      +schema: data_marts
      +materialized: view

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"

clean-targets:
  - "target"
