default:
  target: dev
  outputs:
    data_lake:
      type: postgres
      host: postgres-dbt
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: data_lake
      schema: default
      threads: 4
    
    dev:
      type: postgres
      host: postgres-dbt
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: dev
      schema: default
      threads: 4

    pro:
      type: postgres
      host: postgres-dbt
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: pro
      schema: default
      threads: 4